Use the correct CLI option to enable TDZ in Hermes
bterlson/eshost pull request #138
Opened 2023-10-03 16:16 UTC by gibson042

Fixes #125

2025-01-31 15:29 UTC, leotm approved these changes
nice this worked perfectly earlier when eshost was running hermes cli 0.12.0 (HBC bytecode ver: 89) bin (from esvu/jsvu), i tested locally

```console
➜  npm list -g
/Users/leo/.nvm/versions/node/v22.13.1/lib
├── corepack@0.30.0
├── eshost-cli@9.0.0
├── esvu@1.2.16
└── npm@10.9.2

➜  sed -i '' 's|/Users/leo/.esvu/bin/hermes|/Users/leo/Documents/GitHub/hermes-cli-darwin-v0.12.0/hermes|g' /Users/leo/.eshost-config.json

➜  ls -l /Users/leo/.nvm/versions/node/v22.13.1/bin/eshost
lrwxr-xr-x@ 1 leo  staff  44 31 Jan 13:37 /Users/leo/.nvm/versions/node/v22.13.1/bin/eshost -> ../lib/node_modules/eshost-cli/bin/eshost.js

➜  eshost -e "42"
#### engine262
42

#### hermes

hermes: Unknown command line argument '-fenable-tdz'.  Try: '/Users/leo/Documents/GitHub/hermes-cli-darwin-v0.12.0/hermes -help'

#### javascriptcore
42

#### spidermonkey
42

#### v8
42

#### xs
42


➜  curl -o /Users/leo/.nvm/versions/node/v22.13.1/lib/node_modules/eshost-cli/node_modules/eshost/lib/agents/hermes.js https://raw.githubusercontent.com/tc39/eshost/58370fcbd7183cc5b10b9bd39b7173def13f5db3/lib/agents/hermes.js
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3047  100  3047    0     0  13840      0 --:--:-- --:--:-- --:--:-- 13850

➜  eshost -e "42"
#### engine262
42

#### hermes
42

#### javascriptcore
42

#### spidermonkey
42

#### v8
42

#### xs
42
```

approved if we want to merge this first

but latest eshost pulls in the latest hermes cli 0.13.0 (HBC bytecode ver: 96) bin

where we currently still get similar error

```console
➜  GitHub eshost -e "42"
#### engine262
42

#### hermes

hermes: Unknown command line argument '-Xenable-tdz'.  Try: '/Users/leo/.esvu/bin/hermes -help'

#### javascriptcore
42

#### spidermonkey
42

#### v8
42

#### xs
42
```

i've added a more simple/minimal fix here
- https://github.com/tc39/eshost/pull/145

2025-01-31 17:43 UTC, leotm requested changes
one tiny quirk fix suggestion so it works testing locally

2025-01-31 17:43 UTC, leotm commented on lib/agents/hermes.js
> +      }
```suggestion
      const [_, releaseVersion] = /Hermes release version: (.*)/.exec(stdout);
      const [__, bytecodeVersion] = /HBC bytecode version: (.*)/.exec(stdout);
      if (/^0[.][0-9][.]/.test(releaseVersion)) {
        this.args.unshift('-fenable-tdz');
      } else if (/^0[.]1[012][.]/.test(releaseVersion) && /^(9[7-9]|[1-9]\d{2,})/.test(bytecodeVersion)) {
        this.args.unshift('-Xenable-tdz');
      }
```

2025-01-31 17:43 UTC, leotm commented on lib/agents/hermes.js
> +      }
since v0.13.0 `--version` still shows 0.12.0 😄

```console
➜  hermes-cli-darwin-v0.12.0 ./hermes --version
LLVM (http://llvm.org/):
  LLVH version 8.0.0svn
  Optimized build

Hermes JavaScript compiler and Virtual Machine.
  Hermes release version: 0.12.0
  HBC bytecode version: 89

  Features:
    Zip file input
```

```console
➜  hermes-cli-darwin-v0.13.0 ./hermes --version
LLVM (http://llvm.org/):
  LLVH version 8.0.0svn
  Optimized build

Hermes JavaScript compiler and Virtual Machine.
  Hermes release version: 0.12.0
  HBC bytecode version: 96

  Features:
    Unicode RegExp Property Escapes
    Zip file input
```

2025-01-31 17:43 UTC, leotm commented on lib/agents/hermes.js
> +      }
remembering now [some time ago](https://github.com/facebook/hermes/issues/1371#issuecomment-2052065772) suggesting we show the short commit id too 😄

2025-01-31 17:53 UTC, gibson042 commented on lib/agents/hermes.js
> +      }
```suggestion
      const [_, releaseVersion] = /Hermes release version: (.*)/.exec(stdout);
      const [__, bytecodeVersion] = /HBC bytecode version: (.*)/.exec(stdout);
      if (/^0[.][0-9][.]/.test(releaseVersion)) {
        this.args.unshift('-fenable-tdz');
      } else if (/^0[.]1[012][.]/.test(releaseVersion) && !(+bytecodeVersion >= 96)) {
        this.args.unshift('-Xenable-tdz');
      }
```

2025-01-31 17:55 UTC, leotm commented on lib/agents/hermes.js
> +      }
ah yes i messed up the regex, perfect ^

2025-01-31 17:57 UTC, leotm approved these changes
lgtm

2025-02-04 12:16 UTC, leotm commented
does the change look good @rwaldron?
or might eshost be archived/deprecated soon?
happy to help if you need maintainers

2025-02-04 12:16 UTC, leotm commented
was about to fork till noticed 45 branches / 40 forks
only master and these [five](https://github.com/user-attachments/assets/6adf1d56-b6e5-4280-ad53-6fe59f9e1ccd) forks are visible
[test262-fyi/eshost](https://github.com/test262-fyi/eshost) seems next best option (or to fork from here)

2025-04-08 20:12 UTC, ptomato approved these changes

2025-04-08 20:17 UTC, ryzokuken approved these changes

2025-04-08 20:19 UTC, merged